spring:
  application:
    name: MovieVault

  datasource:
    url: jdbc:postgresql://localhost:5432/movievault
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

movievault:
  security:
    secret: "4VegEgbZidflae5UsdV65X89adwhOUfvVB/btjyonWLxsxSfEJeyWc153ONR7acQ/"
