spring:
  application:
    name: MovieVault

  datasource:
    url:
    username:
    password:
    driver-class-name:

  jpa:
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true